using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using MeetingTranscriber.Models;

namespace MeetingTranscriber.Core.Export;

public static class PdfExporter
{
    static PdfExporter() => QuestPDF.Settings.License = LicenseType.Community;

    public static Task ExportAsync(IEnumerable<TranscriptLine> lines, string title, string filePath)
    {
        var lineList = lines.ToList();
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(t => t.FontSize(11).FontFamily("Arial"));

                page.Header().Text(title).FontSize(16).Bold().FontColor("#1a1a2e");
                page.Content().Column(col =>
                {
                    col.Spacing(4);
                    foreach (var line in lineList)
                    {
                        var ts = TimeSpan.FromSeconds(line.TimestampSec);
                        col.Item().Row(row =>
                        {
                            row.ConstantItem(50).Text($"[{ts:mm\\:ss}]").FontColor("#6b7280").FontSize(9);
                            row.RelativeItem().Text(line.Text);
                        });
                    }
                });
                page.Footer().AlignRight().Text(t =>
                {
                    t.Span("Generated by MeetingTranscriber · ");
                    t.CurrentPageNumber();
                });
            });
        }).GeneratePdf(filePath);

        return Task.CompletedTask;
    }
}
